x-common-env: &common-env
  PGID: 1000
  PUID: 1000
  TZ: Europe/Paris

x-common-deploy: &common-deploy
  restart_policy:
    condition: on-failure
    delay: 5s
    window: 120s

networks:
  backend: {}
  public:
    external: true

services:
 rclone:
    image: rclone/rclone:latest
    read_only: true
    command:
      - rcd
      - --rc-web-gui
      - --rc-web-gui-no-open-browser
      - --rc-addr=:5572
      - --log-level=INFO
      - --rc-user=administrator
      - --rc-pass=$SUDO_PASSWORD
      - --config=/config/rclone/rclone.conf
      - --cache-dir=/tmp/.cache/rclone
    networks:
      - public
    volumes:
      - $STORAGE_PATH:/docker:ro
      - $STORAGE_PATH/core/rclone/config:/config/rclone
      - $STORAGE_PATH/core/rclone/logs:/logs
      - type: tmpfs
        target: /tmp
    environment:
      <<: *common-env
    deploy:
      <<: *common-deploy
      labels:
        # Allow traefik to process this container
        - "traefik.enable=true"
        - "traefik.swarm.lbswarm=true"
        - "traefik.http.routers.rclone.rule=Host(`rclone.$DOMAIN_NAME`)"
        - "traefik.http.routers.rclone.entrypoints=https"
        - "traefik.http.services.rclone.loadbalancer.server.port=5572"
        # Homepage 
        - "homepage.group=Media Management"
        - "homepage.name=Rclone"
        - "homepage.icon=rclone.png"
        - "homepage.href=https://rclone.$DOMAIN_NAME"
        - "homepage.description=A web interface for Rclone."



